---
title: "Results"
author: "Your Name"
format: 
  docx:
    reference-docx: "APA_template.docx"
editor: visual
---

+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| **Variable name** | **Question**                                                                                                                                                                                                                               | **Response options**                                                                                                           |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| exercise          | Exercised excessively  (e.g. felt compelled to exercise, felt uneasy or distressed if unable to exercise)                                                                                                                                  | 1=never; 2=a few times, but it never became a habit; 3=more often                                                              |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_compel         | Have you ever felt compelled to exercise-like you had to do it-to control your body shape or weight?                                                                                                                                       | 1=Yes \| 0=No \| -9=Don't know                                                                                                 |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_distress       | Have you ever felt uneasy or distressed if unable to exercise?                                                                                                                                                                             | 1=Yes \| 0=No \| -9=Don't know                                                                                                 |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_friend         | Have there been times when you declined opportunities to be with friends in order to exercise?                                                                                                                                             | 1=Yes \| 0=No \| -9=Don't know                                                                                                 |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_ill            | Have you exercised despite an injury or illness that would have prevented others from exercising?                                                                                                                                          | 1=Yes \| 0=No \| -9=Don't know                                                                                                 |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_diet           | Have there been times you modified your diet/eating habits if you were unable to exercise for any reason?                                                                                                                                  | 1=Yes \| 0=No \| -9=Don't know                                                                                                 |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_age            | How old were you when you first exercised to control your weight and shape AND felt either compelled to exercise or distressed if unable to exercise?                                                                                      | integer, Min:0, Max: 120                                                                                                       |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_dur            | For how long did you feel compelled to exercise or felt distressed if unable to exercise?                                                                                                                                                  | 1=Less than 1 month \| 2=1 to 2 months \| 3=3 to 5 months \| 4=6-12 months \| 5=More than 1 year \| -9=Don't know              |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_freq           | During these periods, how frequently did you exercise excessively in a week?                                                                                                                                                               | 1=Less than once a week \| 2=At least once a week \| 3=At least twice a week \| 4=Every day/ nearly every day \| -9=Don't know |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_current        | Do you currently exercise to control weight and shape AND feel compelled to exercise or distress if unable to exercise?                                                                                                                    | 1=Yes \| 0=No                                                                                                                  |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| ex_age_last       | How old were you when you stopped exercising to control your weight and shape AND felt either compelled to exercise or distressed if unable to exercise?                                                                                   | integer, Min:0, Max: 120                                                                                                       |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Be_icb_5          | Have you ever used any of the following to compensate for episodes of binge eating or overeating? (Mark all that apply) (choice=Exercised excessively (e.g., felt compelled to exercise, felt uneasy or distressed if unable to exercise)) |                                                                                                                                |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Icb_lowt_5        | Exercised excessively (e.g., felt compelled to exercise, felt uneasy or distressed if unable to exercise)                                                                                                                                  |                                                                                                                                |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| **Scoring Approach**                                                                                                                                                                                                   | **Criteria**                                                                                                                                                                                                                               | **Nested Within**   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 1.  'Q1 Any' \| Participant endorses that they have exercised excessively (e.g. felt compelled to exercise, felt uneasy or distressed if unable to exercise) to control weight or shape 'A few times' or more \| NA \| |                                                                                                                                                                                                                                            |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 2.  'Q1 Regular' \| Participant endorses that they have exercised excessively (e.g. felt compelled to exercise, felt uneasy or distressed if unable to exercise) to control weight or shape 'more often' \| 1          |                                                                                                                                                                                                                                            |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 3.  'Driven/Compulsive Exercise Broad' (Q1 Validation)                                                                                                                                                                 | Q1 Any (#1)                                                                                                                                                                                                                                | 1                   |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Ever felt compelled to exercise == 'YES' OR Ever uneasy or distressed when unable to exercise == 'YES'                                                                                                                                     |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 4.  'Driven/Compulsive Exercise Narrow' (Q1 Validation)                                                                                                                                                                | Q1 Regular (#1, #2)                                                                                                                                                                                                                        | 1, 2                |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Ever felt compelled to exercise == 'YES' OR Ever uneasy or distressed when unable to exercise == 'YES'                                                                                                                                     |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 5.  'Addictive Exercise'                                                                                                                                                                                               | Q1 Regular (#1,#2)                                                                                                                                                                                                                         | 1, 2, 3             |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Driven/Compulsive symptom verified (#3)                                                                                                                                                                                                    |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Duration \>= 3 months                                                                                                                                                                                                                      |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | 1 or more of the following:                                                                                                                                                                                                                |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | -caused to change eating habits                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | -decline opportunities to be with friends                                                                                                                                                                                                  |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | -exercised despite illness or injury                                                                                                                                                                                                       |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 6.  'Excessive Exercise' (with compulsive features)                                                                                                                                                                    | Q1 Regular (#1,#2)                                                                                                                                                                                                                         | 1, 2, 3             |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Driven/Compulsive symptom verified (#3)                                                                                                                                                                                                    |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Duration \>= 1 month                                                                                                                                                                                                                       |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Frequency = 'Every Day' or 'Nearly Every Day'                                                                                                                                                                                              |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 7.  'Compensatory Exercise'                                                                                                                                                                                            | Have you ever used any of the following to compensate for episodes of binge eating or overeating? (Mark all that apply) (choice=Exercised excessively (e.g., felt compelled to exercise, felt uneasy or distressed if unable to exercise)) | NA                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 8.  '**Current** Maladaptive Exercise'                                                                                                                                                                                 | Q1 Any (#1)                                                                                                                                                                                                                                | 1, 3                |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Driven/Compulsive symptom verified                                                                                                                                                                                                         |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Do you *currently* exercise to control weight and shape AND                                                                                                                                                                                |                     |
|                                                                                                                                                                                                                        |                                                                                                                                                                                                                                            |                     |
|                                                                                                                                                                                                                        | Feel compelled to exercise OR distress if unable to exercise? == 'YES'                                                                                                                                                                     |                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
