<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Katherine Schaumberg">

<title>EDGI Exercise Validation Paper Results</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="Validation_Paper_Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Validation_Paper_Analysis_files/libs/quarto-html/quarto.js"></script>
<script src="Validation_Paper_Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Validation_Paper_Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Validation_Paper_Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Validation_Paper_Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Validation_Paper_Analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Validation_Paper_Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Validation_Paper_Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Validation_Paper_Analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">EDGI Exercise Validation Paper Results</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Katherine Schaumberg </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="sample-descriptives" class="level1">
<h1>Sample Descriptives</h1>
<div class="cell">

</div>
<p>Frequencies for the 10 dichotomous/ordinal exercise items with imputed values based on skip patterns (see <a href="sec:scoring">scoring</a>) are provide in <a href="#tbl-ed100kItems">Table&nbsp;1</a>. Median age of onset for those reporting any compulsive exercise in the sample was 16 years and the median age of last report of compulsive exercise was 26 years. Among those who reported any compulsive exercise, 47.72% reported that this was an ongoing symptom.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ed100kItems" class="anchored">

<table><caption>Table&nbsp;1:  Item-level descriptives for ED100k Exercise Items </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:left;"> Response </th>
   <th style="text-align:right;"> Freq </th>
   <th style="text-align:right;"> Percent </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1. Exercised excessively </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:right;"> 945 </td>
   <td style="text-align:right;"> 13.02 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 1. Exercised excessively </td>
   <td style="text-align:left;"> Sometimes </td>
   <td style="text-align:right;"> 1710 </td>
   <td style="text-align:right;"> 23.56 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 1. Exercised excessively </td>
   <td style="text-align:left;"> More Often </td>
   <td style="text-align:right;"> 4604 </td>
   <td style="text-align:right;"> 63.42 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2. Compelled to Exercise </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:right;"> 1205 </td>
   <td style="text-align:right;"> 16.60 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2. Compelled to Exercise </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:right;"> 6024 </td>
   <td style="text-align:right;"> 82.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2. Compelled to Exercise </td>
   <td style="text-align:left;"> Missing </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 0.41 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3. Distressed when unable to exercise </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:right;"> 1485 </td>
   <td style="text-align:right;"> 20.46 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3. Distressed when unable to exercise </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:right;"> 5675 </td>
   <td style="text-align:right;"> 78.18 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3. Distressed when unable to exercise </td>
   <td style="text-align:left;"> Missing </td>
   <td style="text-align:right;"> 99 </td>
   <td style="text-align:right;"> 1.36 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4. Interfering with Friendship </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:right;"> 2643 </td>
   <td style="text-align:right;"> 36.53 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4. Interfering with Friendship </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:right;"> 4266 </td>
   <td style="text-align:right;"> 58.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4. Interfering with Friendship </td>
   <td style="text-align:left;"> Missing </td>
   <td style="text-align:right;"> 326 </td>
   <td style="text-align:right;"> 4.51 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5. Exercising when ill </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:right;"> 2496 </td>
   <td style="text-align:right;"> 34.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5. Exercising when ill </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:right;"> 4481 </td>
   <td style="text-align:right;"> 61.94 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5. Exercising when ill </td>
   <td style="text-align:left;"> Missing </td>
   <td style="text-align:right;"> 258 </td>
   <td style="text-align:right;"> 3.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6. Modified Diet if unable to Exercise </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:right;"> 1599 </td>
   <td style="text-align:right;"> 22.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6. Modified Diet if unable to Exercise </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:right;"> 5515 </td>
   <td style="text-align:right;"> 76.23 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6. Modified Diet if unable to Exercise </td>
   <td style="text-align:left;"> Missing </td>
   <td style="text-align:right;"> 121 </td>
   <td style="text-align:right;"> 1.67 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7. Exercise Duration </td>
   <td style="text-align:left;"> No compulsive exercise </td>
   <td style="text-align:right;"> 1145 </td>
   <td style="text-align:right;"> 15.83 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7. Exercise Duration </td>
   <td style="text-align:left;"> Less than 1 month </td>
   <td style="text-align:right;"> 110 </td>
   <td style="text-align:right;"> 1.52 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7. Exercise Duration </td>
   <td style="text-align:left;"> 1 to 2 months </td>
   <td style="text-align:right;"> 161 </td>
   <td style="text-align:right;"> 2.23 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7. Exercise Duration </td>
   <td style="text-align:left;"> 3 to 5 months </td>
   <td style="text-align:right;"> 332 </td>
   <td style="text-align:right;"> 4.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7. Exercise Duration </td>
   <td style="text-align:left;"> 6-12 months </td>
   <td style="text-align:right;"> 581 </td>
   <td style="text-align:right;"> 8.03 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7. Exercise Duration </td>
   <td style="text-align:left;"> More than 1 year </td>
   <td style="text-align:right;"> 4689 </td>
   <td style="text-align:right;"> 64.81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7. Exercise Duration </td>
   <td style="text-align:left;"> Missing </td>
   <td style="text-align:right;"> 217 </td>
   <td style="text-align:right;"> 3.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8. Exercise Frequency </td>
   <td style="text-align:left;"> No compulsive exercise </td>
   <td style="text-align:right;"> 1145 </td>
   <td style="text-align:right;"> 15.83 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8. Exercise Frequency </td>
   <td style="text-align:left;"> Less than once a week </td>
   <td style="text-align:right;"> 176 </td>
   <td style="text-align:right;"> 2.43 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8. Exercise Frequency </td>
   <td style="text-align:left;"> At least once a week </td>
   <td style="text-align:right;"> 359 </td>
   <td style="text-align:right;"> 4.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8. Exercise Frequency </td>
   <td style="text-align:left;"> At least twice a week </td>
   <td style="text-align:right;"> 1100 </td>
   <td style="text-align:right;"> 15.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8. Exercise Frequency </td>
   <td style="text-align:left;"> Every day/ nearly every day </td>
   <td style="text-align:right;"> 4320 </td>
   <td style="text-align:right;"> 59.71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8. Exercise Frequency </td>
   <td style="text-align:left;"> Missing </td>
   <td style="text-align:right;"> 135 </td>
   <td style="text-align:right;"> 1.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9. Current Exercise </td>
   <td style="text-align:left;"> No History </td>
   <td style="text-align:right;"> 1145 </td>
   <td style="text-align:right;"> 15.83 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9. Current Exercise </td>
   <td style="text-align:left;"> History, Not Current </td>
   <td style="text-align:right;"> 3184 </td>
   <td style="text-align:right;"> 44.01 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9. Current Exercise </td>
   <td style="text-align:left;"> Current </td>
   <td style="text-align:right;"> 2906 </td>
   <td style="text-align:right;"> 40.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Q12. Compensatory Exercise </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:right;"> 3600 </td>
   <td style="text-align:right;"> 49.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Q12. Compensatory Exercise </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:right;"> 3659 </td>
   <td style="text-align:right;"> 50.41 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="preliminary-aim---develop-a-scoring-algorithm" class="level1">
<h1>Preliminary Aim - Develop a scoring algorithm</h1>
<p>The first aim of this paper is to develop a scoring algorithm for a ED100k exercise items in an ED sample based on theoretical literature and available ED100k items which captures and defines rates of:</p>
<p>1. Compulsive Exercise</p>
<ul>
<li><p>Ever and Regular Compulsive Exercise</p></li>
<li><p>Current Compulsive Exercise</p></li>
</ul>
<p>2. Exercise Addiction</p>
<p>3. Excessive Exercise</p>
<p>4. Compensatory Exercise</p>
<p>5. Maladaptive Exercise (Broad)</p>
<section id="sec:scoring" class="level2">
<h2 class="anchored" data-anchor-id="sec:scoring">Scoring</h2>
<p>The ED100k included 12 questions assessing maladaptive exercise. The first question, which all participants were asked, inquires as to whether individuals ever exercised to intentionally control weight and shape (Q1). Only those who endorsed EVER Exercising to intentionally control weight or shape were asked to respond to two additional questions which asked about exercise in more detail, including two questions (Q2, Q3) about whether individuals ever felt compelled to exercise and whether they felt uneasy or distressed if unable to exercise. In a third step, those who reported ever exercising to intentionally control weight and shape and answered ‘Yes’ to either Q2 or Q3 were additionally asked three questions (Q4-Q6) about whether exercise interfered with life activities or diet, along with questions regarding the onset (Q7), duration (Q8), and frequency (Q9) of their compulsive exercise, along with whether they engaged in the behavior currently (Q10) and the last age at which they engaged in the behavior (Q11). In a separate section, all participants were asked whether they had ‘exercised excessively’ specifically to <em>compensate</em> for episodes of binge eating or overeating (Q12). During recoding, those (n = 945) who reported no to Q1 - exercise to control shape and weight, were marked as ‘0’ for all follow-up questions, with the exception of ages (Q10-11), which were retained as missing. Those who reported that they had engaged in exercise to for weight and shape control but ‘No’ to both Q2 &amp; Q3 (n = 200) were marked as ‘0’ for Q4-Q9.</p>
<p>Scoring algorithms for each subconstruct are presented in <a href="#tbl-defs">Table&nbsp;2</a>.</p>
<div id="tbl-defs" class="anchored">
<table class="table">
<caption>Table&nbsp;2: Algorithm defining exercise-related constructs in the ED100k</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 75%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Construct</th>
<th>Criteria</th>
<th>Nested Within</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exercise for Weight Control</td>
<td>To control weight and shape – participant endorses that they have exercised excessively (e.g.&nbsp;felt compelled to exercise, felt uneasy or distressed if unable to exercise) = ‘a few times, but it never became a habit’ or more</td>
<td>NA</td>
</tr>
<tr class="even">
<td>Regular Exercise for Weight Control</td>
<td>To control weight and shape – participant endorses that they have exercised excessively (e.g.&nbsp;felt compelled to exercise, felt uneasy or distressed if unable to exercise) = ‘more often’</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>Compulsive Exercise</td>
<td><p>Exercise for Weight Control +</p>
<p>Ever felt compelled to exercise == ‘YES’ OR Ever uneasy or distressed when unable to exercise == ‘YES’</p></td>
<td>Exercise for Weight Control</td>
</tr>
<tr class="even">
<td>Regular Compulsive Exercise</td>
<td><p>Regular Exercise for Weight Control</p>
<p>Ever felt compelled to exercise == ‘YES’ OR Ever uneasy or distressed when unable to exercise == ‘YES’</p></td>
<td><p>Exercise for Weight Control</p>
<p>Regular Exercise for Weight Control</p>
<p>Compulsive Exercise</p></td>
</tr>
<tr class="odd">
<td>Current Compulsive Exercise</td>
<td><p>Compulsive Exercise</p>
<p>Do you currently exercise to control weight and shape AND feel compelled to exercise or distress if unable to exercise? == ‘YES’</p></td>
<td>Compulsive Exercise</td>
</tr>
<tr class="even">
<td>Addictive Exercise</td>
<td><p>Regular Compulsive Exercise lasting at Least 3 month</p>
<p>1 or more of the following: caused them to change eating habits</p>
<p>-decline opportunities to be with friends</p>
<p>-exercised despite illness or injury</p></td>
<td><p>Exercise for Weight Control</p>
<p>Regular Exercise for Weight Control</p>
<p>Compulsive Exercise</p>
<p>Regular Compulsive Exercise</p></td>
</tr>
<tr class="odd">
<td>Excessive Exercise</td>
<td><p>Compulsive Exercise</p>
<p>Duration &gt;= 1 month</p>
<p>Frequency = ‘Every Day’ or ‘Nearly Every Day’</p></td>
<td><p>Exercise for Weight Control</p>
<p>Compulsive Exercise</p></td>
</tr>
<tr class="even">
<td>Compensatory Exercise</td>
<td>Have you ever used any of the following to compensate for episodes of binge eating or overeating? (Mark all that apply) (choice=Exercised excessively (e.g., felt compelled to exercise, felt uneasy or distressed if unable to exercise))</td>
<td>NA</td>
</tr>
<tr class="odd">
<td>Maladaptive Exercise</td>
<td>Compulsive Exercise == ‘Yes’ OR Compensatory Exercise == ‘Yes’</td>
<td>NA</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="aim-1.-evaluate-patterns-of-response-across-multiple-exercise-constructs-to-identify-the-degree-to-which-these-constructs-overlap-in-membership-or-capture-distinct-groups" class="level1">
<h1>Aim 1. Evaluate patterns of response across multiple exercise constructs, to identify the degree to which these constructs overlap in membership or capture distinct groups</h1>
<p>We hypothesize that those indicating that they have ‘exercise excessively’ more often in the initial screening item will also be likely to meet criteria for compulsive exercise, exercise addiction, and excessive exercise (high sensitivity), and moderately likely to meet criteria for compensatory exercise (moderate sensitivity; high negative predictive value). Specficially, we hypotehsize ensitivity for compulsive exercise, exercise addiction, and excessive exercise based on item 1 will be &gt; 80%. Sensitivity for compensatory exercise from item 1 will be &gt; 60%, with &gt; 80% negative predictive value.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-heatmap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Validation_Paper_Analysis_files/figure-html/fig-heatmap-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Heatmap with percentage of (sub)samples (horizontal axis) meeting criteria for each (sub)construct (vertical axis)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-heatmap">Figure&nbsp;1</a> presents the proportion of the full sample along with subsamples meeting criteria for each (sub)construct</p>
<section id="accuracy-of-q1---excessive-exercise-for-weight-control-to-detect-different-exercise-constructs" class="level2">
<h2 class="anchored" data-anchor-id="accuracy-of-q1---excessive-exercise-for-weight-control-to-detect-different-exercise-constructs">Accuracy of Q1 - ‘Excessive Exercise’ for Weight Control to Detect Different Exercise Constructs</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Q1sensitivity" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Validation_Paper_Analysis_files/figure-html/fig-Q1sensitivity-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Accuracy of Q1 in Detecting Compulsive, Addictive, and Excessive Exercise</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Overall, there was high convergent validity for Q1 with Q2-Q6. Specifically, individuals eating disorders who endorse using exercise to intentionally control weight ‘more often’ are indeed highly likely to engage in this behavior for a substantive period of time – 98.2% of those reporting exercise to intentionally control weight ‘more often’ reported a duration of compulsive exercise &gt; 3 months; a time period of equivalent to diagnostic levels of other intentional weight control behaviors), and to report symptoms consistent with a definition of both compulsive and addictive exercise. <a href="#fig-Q1sensitivity">Figure&nbsp;2</a> reports on the utility of Q1 to capture different exercise constructs assessed in Q2-Q12. The sensitivity and negative predictive values of endorsement of any exercise Q1 in detecting compulsive, addictive, and excessive exercise were forced to 1.0 for those answering that they had ever engaged in any exercise on Q1 by skip logic. Sensitivity to compensatory exercise, was also high – almost all of those who endorsed compensatory exercise also reported excessive exercise for weight loss on Q1. Positive predictive value – the degree to which an affirmative answer to Q1 translated to endorsement of these constructs, varied across constructs. For compulsive exercise, those who endorsed any exercise on Q1 were also very likely to endorse compulsive exercise symptoms. Positive predictive value of those endorsing any exercise on Q1 was somewhat lower for excessive, addictive, and regular compulsive exercise (~.70), and even lower for compensatory exercise (0.58) The positive predictive value rose for these maladaptive exercise constructs when individuals reported exercise ‘more often’. Regarding specificity, there was relatively high specificity for ‘Any’ or more to Q1 for compulsive exercise, which rose to near perfect specificity when the criteria was set at ‘More Often’. Specificty was low for ‘Any’ exercise in Q1 capturing addictive, excessive, and regular compulsive exercise, but rose significantly when criteria was set at ‘More Often’. Specificity was also low for ‘Any’ exercise in Q1 capturing compensatory exercise, and rose modestly when the Q1 criteria was set to ‘More Often’. When considering overall accuracy, endorsement of ‘any’ exercise in Q1 best captured those who endorsed <em>any</em> history of compulsive exercise, whereas, for the more stringent criteria of regular compulsive or addictive exercise, endorsement of exercise ‘More Often’ in Q1 demonstrated good accuracy. Overall, the vast majority of individuals with eating disorders who reporting regular exercise for weight loss to control weight and shape in Q1 go on to report that this exercise was compulsive, and that they also experienced life interfering sequellae of this behavior. Further, regarding specific addictive exercise symptoms, the modal number of exercise interference items was all 3. While Q1 accurately defined those experiencing compulsive and addictive exercise with little additional information provided from follow-up questions, the same was not true for excessive exercise and compensatory exercise – additional questions may be necessary to define excessive and compensatory exercise with the highest levels of accuracy, and endorsement of these constructs do not entirely overlap with endorsement of other maladpative exercise symptoms.</p>
</section>
</section>
<section id="aim-2.-evaluate-convergent-and-discriminant-validity-between-history-of-maladaptive-and-compulsive-exercise-and-current-compulsive-exercise-perfectionism-and-ocd-sympotms" class="level1">
<h1>Aim 2. Evaluate Convergent and Discriminant Validity between history of <em>maladaptive</em> and <em>compulsive</em> exercise and: current compulsive exercise, perfectionism, and OCD sympotms</h1>
<p>H2a: Individuals who do not report <em>any</em> <em>history</em> of maladaptive and compulsive exercise will not report current compulsive exercise (high negative predictive value). <em>&gt;90% negative predictive value of history to 1. Current driven exercise to manage weight/shape on the EDEQ, 2. Current compulsive exercise on the CET</em></p>
<p><a href="#fig-npv">Figure&nbsp;3</a> demonstrates confusion matrix components for history of compulsive and maladaptive exercise endorsement on the ED100k and current compulsive exercise endorsement assessed by 1. meeting CET clinical cutoff and 2. endorsement of EDEQ (any and at least weekly) driven exercise in the past 28 days. As hypothesized, both compulsive and maladaptive exercise had a high negative predictive value – those who did not endorse any history of compulsive or maladaptive exercise were unlikely to endorse current compulsive or driven exercise on the CET and EDEQ. Negative predictive values for both CET clinical cutoff and weekly or more maladaptive exercise (4x or more over the past 28 days) were &gt; 0.9. Negative predictive values were slightly lower for reports of any driven exercise over the past 28 days (~ 0.85), indicating that some individuals who endorse no history of compulsive exercise may engage in this behavior at relatively low frequency.<em>Accuracy</em>, <em>positive predictive value</em>, and <em>specificity</em> were all low, indicating that many individuals who reported history of compulsive exercise on the ED100k were not engaging in this behavior at the time of assessment.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-npv" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Validation_Paper_Analysis_files/figure-html/fig-npv-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Confusion matrix components of compulsive and maladaptive history vs.&nbsp;current CET and EDEQ exercise</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="cet-scores-and-edeq-driven-exercise-across-ed100k-compulsive-exercise-history-and-current-endorsement" class="level2">
<h2 class="anchored" data-anchor-id="cet-scores-and-edeq-driven-exercise-across-ed100k-compulsive-exercise-history-and-current-endorsement">CET scores and EDEQ driven exercise across ED100k compulsive exercise history and current endorsement</h2>
<p>H2b: Comparing across groups who report no history of compulsive exercise, history of, but not current, compulsive exercise, and those with current compulsive exercise on the ED100k, those who report ED100k current compulsive exercise will report highest CET scores (total, and all subscales except for exercise enjoyment). Those reporting history of, but not current, compulsive exercise will report intermediate CET scores – higher than those reporting no history of compulsive exercise on the ED100k but lower than those reporting current compulsive exercise. We also expect thsoe reporting current compulsive exercise on the ED100k to be more likely to reach the CET clinical cutoff and report more days of driven exercise over the past 28 days on the EDEQ.</p>
<p>Overall, 15.83% of the sample reported No history of compulsive exercise, 44.01% reported a history of compulsive exercise that was not current, and 40.17% reported current compulsive exercise.</p>
<p>Boxplots with median standardized scores on all CET subscales along with CET total score is presented in <a href="#fig-CETsubs">Figure&nbsp;4</a>. To formally test the hypothesis that those with reporting ED100k current compulsive exercise would also report the highest scores on the CET, we completed a series of ANOVAs comparing those with reporting no compulsive exercise, history of compulsive exercise only, and current compulsive exercise on current CET scores, p &lt; .05 for all subscales and global, and calculation of Cohen’s d effect sizes.*</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-CETsubs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Validation_Paper_Analysis_files/figure-html/fig-CETsubs-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Median standardized CET subscale scores across those reporting no compulsive exercise, compulsive exercise history (not current), and current compulsive exercise on the ED100k</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#tbl-CETANOVA">Table&nbsp;3</a> reports ANOVA output for each CET subscale, comparing across the three groups of individuals who report no compulsive exercise, compulsive exercise history but not current compulsive exercise, and both history and current compulsive exercise on the ED100k. All omnibus tests reach significance.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-CETANOVA" class="anchored">

<table><caption>Table&nbsp;3:  Omnibus ANOVA results comparing groups with current, history only, and no history of compulsive exercise on the ED100k on CET subscales </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Model </th>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> sumsq </th>
   <th style="text-align:right;"> meansq </th>
   <th style="text-align:right;"> statistic </th>
   <th style="text-align:left;"> p.value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Enjoyment </td>
   <td style="text-align:left;"> ED100k History/Current Compulsive Exercise </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1143.95 </td>
   <td style="text-align:right;"> 571.98 </td>
   <td style="text-align:right;"> 327.21 </td>
   <td style="text-align:left;"> 1.550e-133 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Enjoyment </td>
   <td style="text-align:left;"> Residual </td>
   <td style="text-align:right;"> 4570 </td>
   <td style="text-align:right;"> 7988.46 </td>
   <td style="text-align:right;"> 1.75 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mood Improve </td>
   <td style="text-align:left;"> ED100k History/Current Compulsive Exercise </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1328.57 </td>
   <td style="text-align:right;"> 664.29 </td>
   <td style="text-align:right;"> 479.63 </td>
   <td style="text-align:left;"> 5.767e-190 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mood Improve </td>
   <td style="text-align:left;"> Residual </td>
   <td style="text-align:right;"> 4612 </td>
   <td style="text-align:right;"> 6387.64 </td>
   <td style="text-align:right;"> 1.39 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Avoidance </td>
   <td style="text-align:left;"> ED100k History/Current Compulsive Exercise </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 3793.80 </td>
   <td style="text-align:right;"> 1896.90 </td>
   <td style="text-align:right;"> 1427.87 </td>
   <td style="text-align:left;"> 0.000e+00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Avoidance </td>
   <td style="text-align:left;"> Residual </td>
   <td style="text-align:right;"> 4594 </td>
   <td style="text-align:right;"> 6103.03 </td>
   <td style="text-align:right;"> 1.33 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rigidity </td>
   <td style="text-align:left;"> ED100k History/Current Compulsive Exercise </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2854.95 </td>
   <td style="text-align:right;"> 1427.48 </td>
   <td style="text-align:right;"> 927.38 </td>
   <td style="text-align:left;"> 0.000e+00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rigidity </td>
   <td style="text-align:left;"> Residual </td>
   <td style="text-align:right;"> 4565 </td>
   <td style="text-align:right;"> 7026.69 </td>
   <td style="text-align:right;"> 1.54 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wt Control </td>
   <td style="text-align:left;"> ED100k History/Current Compulsive Exercise </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1858.56 </td>
   <td style="text-align:right;"> 929.28 </td>
   <td style="text-align:right;"> 717.69 </td>
   <td style="text-align:left;"> 4.113e-272 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wt Control </td>
   <td style="text-align:left;"> Residual </td>
   <td style="text-align:right;"> 4615 </td>
   <td style="text-align:right;"> 5975.63 </td>
   <td style="text-align:right;"> 1.29 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:left;"> ED100k History/Current Compulsive Exercise </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 17554.96 </td>
   <td style="text-align:right;"> 8777.48 </td>
   <td style="text-align:right;"> 180.19 </td>
   <td style="text-align:left;"> 4.283e-77 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:left;"> Residual </td>
   <td style="text-align:right;"> 7232 </td>
   <td style="text-align:right;"> 352287.57 </td>
   <td style="text-align:right;"> 48.71 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:left;"> NA </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p><a href="#tbl-CETcontrasts">Table&nbsp;4</a> presents specific contrasts between each group, using a Tukey’s HSD approach with an adjusted alpha to compute confidence intervals of 0.0028 - accounting for 18 contrasts. All contrasts reach significance (confidence intervals of differences not overlapping ‘0’). Cohen’s D effects suggest a pattern of moderate effect size when comparing those with no history of compulsive exercise to those with a history, but not current, compulsive exercise and when comparing those with history vs.&nbsp;current compulsive exercise. Comparison of those with no history of compulsive exercise vs.&nbsp;current compulsive exercise consistently demonstrated large effects. For all subscales with the exception of the enjoyment subscale, effects indicated that those with current compulsive exercise scored highest, while those with no history of compulsive exercise scored the highest on the lack of exercise enjoyment subscale.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-CETcontrasts" class="anchored">

<table><caption>Table&nbsp;4:  Contrasts for each of the five CET subscales and the CET Total across those with and without history and current compulsive exercise as reported on the ED100k </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:left;"> Contrast </th>
   <th style="text-align:left;"> Difference </th>
   <th style="text-align:right;"> CohensD </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Enjoy </td>
   <td style="text-align:left;"> No vs Hx of Exercise </td>
   <td style="text-align:left;"> -0.78 ( -0.986, -0.574 ) </td>
   <td style="text-align:right;"> 0.553 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Enjoy </td>
   <td style="text-align:left;"> No vs. Current Exercise </td>
   <td style="text-align:left;"> -1.444 ( -1.653, -1.235 ) </td>
   <td style="text-align:right;"> 1.169 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Enjoy </td>
   <td style="text-align:left;"> Hx vs. Current Exercise </td>
   <td style="text-align:left;"> -0.664 ( -0.817, -0.511 ) </td>
   <td style="text-align:right;"> 0.506 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mood Improve </td>
   <td style="text-align:left;"> No vs Hx of Exercise </td>
   <td style="text-align:left;"> 0.818 ( 0.635, 1.001 ) </td>
   <td style="text-align:right;"> -0.650 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mood Improve </td>
   <td style="text-align:left;"> No vs. Current Exercise </td>
   <td style="text-align:left;"> 1.539 ( 1.354, 1.724 ) </td>
   <td style="text-align:right;"> -1.342 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mood Improve </td>
   <td style="text-align:left;"> Hx vs. Current Exercise </td>
   <td style="text-align:left;"> 0.722 ( 0.586, 0.858 ) </td>
   <td style="text-align:right;"> -0.635 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rigidity </td>
   <td style="text-align:left;"> No vs Hx of Exercise </td>
   <td style="text-align:left;"> 0.73 ( 0.536, 0.924 ) </td>
   <td style="text-align:right;"> -0.566 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rigidity </td>
   <td style="text-align:left;"> No vs. Current Exercise </td>
   <td style="text-align:left;"> 2.07 ( 1.873, 2.267 ) </td>
   <td style="text-align:right;"> -1.742 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rigidity </td>
   <td style="text-align:left;"> Hx vs. Current Exercise </td>
   <td style="text-align:left;"> 1.34 ( 1.197, 1.483 ) </td>
   <td style="text-align:right;"> -1.081 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wt Control </td>
   <td style="text-align:left;"> No vs Hx of Exercise </td>
   <td style="text-align:left;"> 0.698 ( 0.521, 0.875 ) </td>
   <td style="text-align:right;"> -0.565 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wt Control </td>
   <td style="text-align:left;"> No vs. Current Exercise </td>
   <td style="text-align:left;"> 1.714 ( 1.535, 1.893 ) </td>
   <td style="text-align:right;"> -1.674 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wt Control </td>
   <td style="text-align:left;"> Hx vs. Current Exercise </td>
   <td style="text-align:left;"> 1.016 ( 0.886, 1.146 ) </td>
   <td style="text-align:right;"> -0.893 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Avoidance </td>
   <td style="text-align:left;"> No vs Hx of Exercise </td>
   <td style="text-align:left;"> 0.717 ( 0.537, 0.897 ) </td>
   <td style="text-align:right;"> -0.653 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Avoidance </td>
   <td style="text-align:left;"> No vs. Current Exercise </td>
   <td style="text-align:left;"> 2.313 ( 2.131, 2.495 ) </td>
   <td style="text-align:right;"> -2.010 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Avoidance </td>
   <td style="text-align:left;"> Hx vs. Current Exercise </td>
   <td style="text-align:left;"> 1.597 ( 1.464, 1.73 ) </td>
   <td style="text-align:right;"> -1.340 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:left;"> No vs Hx of Exercise </td>
   <td style="text-align:left;"> 1.479 ( 0.618, 2.34 ) </td>
   <td style="text-align:right;"> -0.241 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:left;"> No vs. Current Exercise </td>
   <td style="text-align:left;"> 4.094 ( 3.223, 4.965 ) </td>
   <td style="text-align:right;"> -0.552 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:left;"> Hx vs. Current Exercise </td>
   <td style="text-align:left;"> 2.615 ( 1.974, 3.256 ) </td>
   <td style="text-align:right;"> -0.361 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell">

</div>
<p>The proportion of individuals meeting the clinical cutoff for current compulsive exericse on the CET varied as expected by endorsement of historical and current endorsement of compulsive exercise on the ED100k. Only 5.76% of individuals who reported no history of compuslive exercise met current CET clinical cutoff, while 18.78% of those reporting history, but not current compulsive exercise met clinical cutoff on the CET, and 62.76% of individuals reporting both historical and current compulsive exercise on the ED100k met clinical cutoff for compulsive exercise on the CET. Using a multinomial logistic regression approach with ‘No Compulsive Exercise History’ on the ED100k coded as the reference category, those reporting compulsive exercise history, but not current exercise had an odds ratio of 3.78 and those reporting current compulsive exercise had an odds ratio of 27.57, indicating significant convergent validity of reports of current compulsive exericse on the ED100k (4 items comprising the historical and current compulsive exercise definition) and meeting clinical cutoff clinical cutoff on the 24-item CET. Regarding the number of days in the past 28 that participants reported engaging in ‘driven’ or ‘compulsive exercise on the EDEQ, outcomes were zero-inflated in the ’No History of Compulsive Exercise’ and ‘History but No Current Compulsive Exercise’ groups (see <a href="#fig-EDEQplot">Figure&nbsp;5</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-EDEQplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Validation_Paper_Analysis_files/figure-html/fig-EDEQplot-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: ED100k Compulsive Exercise vs.&nbsp;EDEQ Exercise Frequency</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A zero-inflated poisson regression model compared those with “History, but Not Current’ and those with ‘Current Compulsive Exercise’ to the ‘No History of Compulsive Exercise’ (reference) group on number of days with driven exercise in the past month. Results are presented in <a href="#tbl-EDEQZin">Table&nbsp;5</a> (including odds ratios (ORs) for the zero portion of the model and incident risk ratios (IRRs) for the count portion). Results indicate that those who report current compulsive exercise on the ED100k are less likely to hvae zero values for EDEQ-assessed exericse in the past 28 days, and report higher counts of exercise days when they do exercise. Those reporting history of, but not current, compulsive exericse on the ED100k are similarly less likely to report zero days of driven exercise on the EDEQ as compared to those who report no history of compulsive exercise, though the count portion of the model indicates that those reporting history, but not current, compulsive exercise are reporting low numbers of exercise days when it occurs, lower than those who report no history of compulsive exercise.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-EDEQZin" class="anchored">

<table><caption>Table&nbsp;5:  Zero-inflated Model Coefficients for ED100k Compulsive Exercise Predicting EDEQ Driven Exercise Days (past 28 days) </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Term </th>
   <th style="text-align:left;"> Model Part </th>
   <th style="text-align:right;"> Estimate </th>
   <th style="text-align:right;"> Std. Error </th>
   <th style="text-align:right;"> IRR </th>
   <th style="text-align:right;"> OR </th>
   <th style="text-align:right;"> z value </th>
   <th style="text-align:left;"> Pr(&gt;|z|) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:left;"> Count </td>
   <td style="text-align:right;"> 2.054 </td>
   <td style="text-align:right;"> 0.029 </td>
   <td style="text-align:right;"> 7.798 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> 70.380 </td>
   <td style="text-align:left;"> 0.00e+00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> History vs. No History </td>
   <td style="text-align:left;"> Count </td>
   <td style="text-align:right;"> -0.255 </td>
   <td style="text-align:right;"> 0.033 </td>
   <td style="text-align:right;"> 0.775 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> -7.704 </td>
   <td style="text-align:left;"> 1.32e-14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Current vs. No History </td>
   <td style="text-align:left;"> Count </td>
   <td style="text-align:right;"> 0.613 </td>
   <td style="text-align:right;"> 0.030 </td>
   <td style="text-align:right;"> 1.846 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> 20.600 </td>
   <td style="text-align:left;"> 2.72e-94 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:left;"> Zero </td>
   <td style="text-align:right;"> 1.694 </td>
   <td style="text-align:right;"> 0.089 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> 5.441 </td>
   <td style="text-align:right;"> 19.131 </td>
   <td style="text-align:left;"> 1.39e-81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> History vs. No History </td>
   <td style="text-align:left;"> Zero </td>
   <td style="text-align:right;"> -0.644 </td>
   <td style="text-align:right;"> 0.099 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> 0.525 </td>
   <td style="text-align:right;"> -6.518 </td>
   <td style="text-align:left;"> 7.11e-11 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Current vs. No History </td>
   <td style="text-align:left;"> Zero </td>
   <td style="text-align:right;"> -3.249 </td>
   <td style="text-align:right;"> 0.103 </td>
   <td style="text-align:right;"> NA </td>
   <td style="text-align:right;"> 0.039 </td>
   <td style="text-align:right;"> -31.461 </td>
   <td style="text-align:left;"> 2.98e-217 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="perfectionism-and-ocd-symptoms" class="level2">
<h2 class="anchored" data-anchor-id="perfectionism-and-ocd-symptoms">Perfectionism and OCD Symptoms</h2>
<p>In addition to convergent validity across current exercise measures, we also examined both convert and discriminant validity by examining those with vs.&nbsp;without history of maladaptive and compulsive exercise on subscales of the Frost MPS indexing maladaptive perfectionism along with subscale and total scores for the OCI-R</p>
<p>H2c: Within diagnostic groups - those with vs.&nbsp;without history of maladaptive exercise will report higher Frost MPS (Maladaptive) and OCD symptoms. <em>t-tests within diagnostic groups comparing frost MPS and OCI-R/OCI-12 subscale scores across those with vs.&nbsp;without history of maladpative exercise, expected p &lt; 0.05 adjusted for multiple comparisons across subscale. We also include calculation of Cohen’s d effect sizes</em></p>
<p>H2d: Associations with the MPS and OCD measure will be weaker than with the CET and EDEQ exercise item. <em>We will interpret patterns of ES across these scales</em></p>
<p>KS Note – Currently do not have access to this data in the dataset</p>
</section>
</section>
<section id="aim-3.-demonstrate-prevalence-of-maladaptive-broad-compulsive-addictive-excessive-and-compensatory-exercise-across-diagnostic-groups" class="level1">
<h1>Aim 3. Demonstrate Prevalence of Maladaptive (Broad), Compulsive, Addictive, Excessive, and Compensatory Exercise across Diagnostic Groups</h1>
<p>H3a. Maladaptive exercise, compulsive exercise, and exercise addiction will be a common symptom across diagnoses. We expect that these constructs will be more common in AN and BN than BED. <em>Rates of maladaptive exercise, compulsive exercise, excessive exercise, and exercise addiction will all be &gt; 50% in AN and BN presentations; &gt; 20% in BED. Multinomial logisitc regression with AN only as reference group will show higher rates in AN only as compared to BN only, BN-BED, and BED only groups</em></p>
<p>H3b. Compensatory exercise will be more common among those with AN mixed and BN as compared to AN only . <em>Multinomial logistic regression with AN group as reference – AN mixed, BN, and BN-BED mixed groups will report higher levels of compensatory exercise than the AN only group. BED only will report similar levels of compensatory exercise to AN only</em></p>
<div class="cell">

</div>
<p>Among individuals in the US EDGI data, 41.64% of the sample reported AN as their only diagnosis, 22.44% of the sample reported AN plus another diagnosis (AN mixed),12.37% reported a diagnosis of BN only, 9.11% reported a diagnosis of BED only (the smallest cell size: 661), and 14.44% reported both a BN and BED diagnosis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dxgroups" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Validation_Paper_Analysis_files/figure-html/fig-dxgroups-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Percentage within each diganostic group reporting differing exercise constructs</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Rates of addictive, compensatory, compulsive, excessive, and regular compulsive exercise across diagnostic groups are presented in <a href="#fig-dxgroups">Figure&nbsp;6</a>. History of addictive, regular compuslive, and excessive exercise were all highest in an absolute sense among groups reporting history of AN. History of Compulsive Exercise was reported most frequently in the AN, AN-Mixed Diagnosis, and BN groups, around 60% in each of these diagnostic groups reporting history of regular engagment of compulsive exericse, and the majority reporting at least some history of this behavior. Output from multinomial logistic regression mdoels using AN only as the reference group are presented in <a href="#tbl-dxgroups">Table&nbsp;6</a>. An adjusted p-value of 0.0017 was used to account for 28 multiple comparisons in the multinomial models. Overall, all other diagnostic groups were substantially more likely to engage in compensatory exercise, with the AN Mixed diagnosis group showing similar odds of engagement in compulsive, regular compulsive, addictive, and excessive exercise relative to AN only. The BN, BED, and BN-BED mixed groups were less likely than the AN only group to report history of addictive, compulsive, regular compulsive, and excessive exercise. With regards to overall maladaptive exericse, the BN-BED and BED only groups showed lower engagement in any form of maladaptive exercise relative to the AN only group.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-dxgroups" class="anchored">

<table><caption>Table&nbsp;6:  Multinomial Logisitc Regression Output and Odds Ratios (Compared to AN only) for each exercise construct. </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> DV </th>
   <th style="text-align:left;"> Case Status </th>
   <th style="text-align:right;"> Odds Ratio </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> std.error </th>
   <th style="text-align:left;"> p.value </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Compensatory </td>
   <td style="text-align:left;"> AN Mixed </td>
   <td style="text-align:right;"> 17.409 </td>
   <td style="text-align:right;"> 2.857 </td>
   <td style="text-align:right;"> 0.080 </td>
   <td style="text-align:left;"> 6.63e-282 </td>
   <td style="text-align:right;"> 2.608 </td>
   <td style="text-align:right;"> 3.106 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Compensatory </td>
   <td style="text-align:left;"> BED </td>
   <td style="text-align:right;"> 1.725 </td>
   <td style="text-align:right;"> 0.545 </td>
   <td style="text-align:right;"> 0.093 </td>
   <td style="text-align:left;"> 5.12e-09 </td>
   <td style="text-align:right;"> 0.254 </td>
   <td style="text-align:right;"> 0.837 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Compensatory </td>
   <td style="text-align:left;"> BN </td>
   <td style="text-align:right;"> 12.635 </td>
   <td style="text-align:right;"> 2.536 </td>
   <td style="text-align:right;"> 0.092 </td>
   <td style="text-align:left;"> 1.35e-166 </td>
   <td style="text-align:right;"> 2.249 </td>
   <td style="text-align:right;"> 2.824 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Compensatory </td>
   <td style="text-align:left;"> BN-BED Mixed </td>
   <td style="text-align:right;"> 6.868 </td>
   <td style="text-align:right;"> 1.927 </td>
   <td style="text-align:right;"> 0.079 </td>
   <td style="text-align:left;"> 1.43e-132 </td>
   <td style="text-align:right;"> 1.681 </td>
   <td style="text-align:right;"> 2.172 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Compulsive </td>
   <td style="text-align:left;"> AN Mixed </td>
   <td style="text-align:right;"> 1.094 </td>
   <td style="text-align:right;"> 0.090 </td>
   <td style="text-align:right;"> 0.106 </td>
   <td style="text-align:left;"> 3.97e-01 </td>
   <td style="text-align:right;"> -0.242 </td>
   <td style="text-align:right;"> 0.422 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Compulsive </td>
   <td style="text-align:left;"> BED </td>
   <td style="text-align:right;"> 0.097 </td>
   <td style="text-align:right;"> -2.333 </td>
   <td style="text-align:right;"> 0.099 </td>
   <td style="text-align:left;"> 8.84e-122 </td>
   <td style="text-align:right;"> -2.644 </td>
   <td style="text-align:right;"> -2.023 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Compulsive </td>
   <td style="text-align:left;"> BN </td>
   <td style="text-align:right;"> 0.692 </td>
   <td style="text-align:right;"> -0.368 </td>
   <td style="text-align:right;"> 0.115 </td>
   <td style="text-align:left;"> 1.42e-03 </td>
   <td style="text-align:right;"> -0.729 </td>
   <td style="text-align:right;"> -0.008 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Compulsive </td>
   <td style="text-align:left;"> BN-BED Mixed </td>
   <td style="text-align:right;"> 0.364 </td>
   <td style="text-align:right;"> -1.011 </td>
   <td style="text-align:right;"> 0.096 </td>
   <td style="text-align:left;"> 5.76e-26 </td>
   <td style="text-align:right;"> -1.311 </td>
   <td style="text-align:right;"> -0.712 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CET Clinical Cutoff </td>
   <td style="text-align:left;"> AN Mixed </td>
   <td style="text-align:right;"> 1.181 </td>
   <td style="text-align:right;"> 0.167 </td>
   <td style="text-align:right;"> 0.079 </td>
   <td style="text-align:left;"> 3.40e-02 </td>
   <td style="text-align:right;"> -0.079 </td>
   <td style="text-align:right;"> 0.412 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CET Clinical Cutoff </td>
   <td style="text-align:left;"> BED </td>
   <td style="text-align:right;"> 0.304 </td>
   <td style="text-align:right;"> -1.191 </td>
   <td style="text-align:right;"> 0.145 </td>
   <td style="text-align:left;"> 2.21e-16 </td>
   <td style="text-align:right;"> -1.644 </td>
   <td style="text-align:right;"> -0.738 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CET Clinical Cutoff </td>
   <td style="text-align:left;"> BN </td>
   <td style="text-align:right;"> 1.138 </td>
   <td style="text-align:right;"> 0.129 </td>
   <td style="text-align:right;"> 0.100 </td>
   <td style="text-align:left;"> 1.94e-01 </td>
   <td style="text-align:right;"> -0.182 </td>
   <td style="text-align:right;"> 0.440 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CET Clinical Cutoff </td>
   <td style="text-align:left;"> BN-BED Mixed </td>
   <td style="text-align:right;"> 0.736 </td>
   <td style="text-align:right;"> -0.306 </td>
   <td style="text-align:right;"> 0.098 </td>
   <td style="text-align:left;"> 1.77e-03 </td>
   <td style="text-align:right;"> -0.612 </td>
   <td style="text-align:right;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Addictive </td>
   <td style="text-align:left;"> AN Mixed </td>
   <td style="text-align:right;"> 1.044 </td>
   <td style="text-align:right;"> 0.043 </td>
   <td style="text-align:right;"> 0.068 </td>
   <td style="text-align:left;"> 5.28e-01 </td>
   <td style="text-align:right;"> -0.169 </td>
   <td style="text-align:right;"> 0.255 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Addictive </td>
   <td style="text-align:left;"> BED </td>
   <td style="text-align:right;"> 0.086 </td>
   <td style="text-align:right;"> -2.458 </td>
   <td style="text-align:right;"> 0.112 </td>
   <td style="text-align:left;"> 7.16e-107 </td>
   <td style="text-align:right;"> -2.808 </td>
   <td style="text-align:right;"> -2.109 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Addictive </td>
   <td style="text-align:left;"> BN </td>
   <td style="text-align:right;"> 0.649 </td>
   <td style="text-align:right;"> -0.433 </td>
   <td style="text-align:right;"> 0.079 </td>
   <td style="text-align:left;"> 4.97e-08 </td>
   <td style="text-align:right;"> -0.680 </td>
   <td style="text-align:right;"> -0.185 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Addictive </td>
   <td style="text-align:left;"> BN-BED Mixed </td>
   <td style="text-align:right;"> 0.373 </td>
   <td style="text-align:right;"> -0.986 </td>
   <td style="text-align:right;"> 0.074 </td>
   <td style="text-align:left;"> 2.22e-40 </td>
   <td style="text-align:right;"> -1.217 </td>
   <td style="text-align:right;"> -0.754 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Regular Compulsive </td>
   <td style="text-align:left;"> AN Mixed </td>
   <td style="text-align:right;"> 0.996 </td>
   <td style="text-align:right;"> -0.004 </td>
   <td style="text-align:right;"> 0.069 </td>
   <td style="text-align:left;"> 9.57e-01 </td>
   <td style="text-align:right;"> -0.219 </td>
   <td style="text-align:right;"> 0.211 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Regular Compulsive </td>
   <td style="text-align:left;"> BED </td>
   <td style="text-align:right;"> 0.091 </td>
   <td style="text-align:right;"> -2.392 </td>
   <td style="text-align:right;"> 0.106 </td>
   <td style="text-align:left;"> 3.63e-112 </td>
   <td style="text-align:right;"> -2.724 </td>
   <td style="text-align:right;"> -2.060 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Regular Compulsive </td>
   <td style="text-align:left;"> BN </td>
   <td style="text-align:right;"> 0.622 </td>
   <td style="text-align:right;"> -0.475 </td>
   <td style="text-align:right;"> 0.080 </td>
   <td style="text-align:left;"> 2.91e-09 </td>
   <td style="text-align:right;"> -0.725 </td>
   <td style="text-align:right;"> -0.225 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Regular Compulsive </td>
   <td style="text-align:left;"> BN-BED Mixed </td>
   <td style="text-align:right;"> 0.364 </td>
   <td style="text-align:right;"> -1.010 </td>
   <td style="text-align:right;"> 0.074 </td>
   <td style="text-align:left;"> 2.80e-42 </td>
   <td style="text-align:right;"> -1.241 </td>
   <td style="text-align:right;"> -0.778 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Excessive </td>
   <td style="text-align:left;"> AN Mixed </td>
   <td style="text-align:right;"> 1.147 </td>
   <td style="text-align:right;"> 0.138 </td>
   <td style="text-align:right;"> 0.068 </td>
   <td style="text-align:left;"> 4.44e-02 </td>
   <td style="text-align:right;"> -0.076 </td>
   <td style="text-align:right;"> 0.351 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Excessive </td>
   <td style="text-align:left;"> BED </td>
   <td style="text-align:right;"> 0.148 </td>
   <td style="text-align:right;"> -1.907 </td>
   <td style="text-align:right;"> 0.102 </td>
   <td style="text-align:left;"> 3.53e-78 </td>
   <td style="text-align:right;"> -2.225 </td>
   <td style="text-align:right;"> -1.589 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Excessive </td>
   <td style="text-align:left;"> BN </td>
   <td style="text-align:right;"> 0.629 </td>
   <td style="text-align:right;"> -0.463 </td>
   <td style="text-align:right;"> 0.080 </td>
   <td style="text-align:left;"> 6.05e-09 </td>
   <td style="text-align:right;"> -0.711 </td>
   <td style="text-align:right;"> -0.214 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Excessive </td>
   <td style="text-align:left;"> BN-BED Mixed </td>
   <td style="text-align:right;"> 0.460 </td>
   <td style="text-align:right;"> -0.777 </td>
   <td style="text-align:right;"> 0.075 </td>
   <td style="text-align:left;"> 2.85e-25 </td>
   <td style="text-align:right;"> -1.010 </td>
   <td style="text-align:right;"> -0.543 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Maladaptive </td>
   <td style="text-align:left;"> AN Mixed </td>
   <td style="text-align:right;"> 1.254 </td>
   <td style="text-align:right;"> 0.226 </td>
   <td style="text-align:right;"> 0.111 </td>
   <td style="text-align:left;"> 4.12e-02 </td>
   <td style="text-align:right;"> -0.120 </td>
   <td style="text-align:right;"> 0.572 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Maladaptive </td>
   <td style="text-align:left;"> BED </td>
   <td style="text-align:right;"> 0.099 </td>
   <td style="text-align:right;"> -2.311 </td>
   <td style="text-align:right;"> 0.099 </td>
   <td style="text-align:left;"> 5.91e-120 </td>
   <td style="text-align:right;"> -2.621 </td>
   <td style="text-align:right;"> -2.002 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Maladaptive </td>
   <td style="text-align:left;"> BN </td>
   <td style="text-align:right;"> 0.714 </td>
   <td style="text-align:right;"> -0.337 </td>
   <td style="text-align:right;"> 0.117 </td>
   <td style="text-align:left;"> 3.85e-03 </td>
   <td style="text-align:right;"> -0.702 </td>
   <td style="text-align:right;"> 0.027 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Maladaptive </td>
   <td style="text-align:left;"> BN-BED Mixed </td>
   <td style="text-align:right;"> 0.396 </td>
   <td style="text-align:right;"> -0.927 </td>
   <td style="text-align:right;"> 0.097 </td>
   <td style="text-align:left;"> 1.70e-21 </td>
   <td style="text-align:right;"> -1.231 </td>
   <td style="text-align:right;"> -0.623 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>